### PR TITLE
Revert "make a gitignore"

### PR DESCRIPTION
**Pull request by fakebitpolytechnic**
Reverts dorkbotlondon/dorkbotlondon.github.io#3

hey Dan weirdly this causes the front page to display the previous event http://dorkbotlondon.org/ and dorkbotlondon.org/91 stops displaying, just reverting to see if that fixes it..?

### CODE REVIEW

**Comment by danstowell** [comment]
it's really unlikely that the gitignore is doing this! probably the other content (#2). I haven't looked at the logic for choosing the homepage

**Comment by danstowell** [comment]
@jonty?

**Comment by Jonty** [comment]
I'll have a look this weekend, been dealing with family things and not had any free time to dig into this.

Related: I've got an .mbox file that is a complete archive of the dorkbot mailing lists with all announcements going back to the very first one, it's much more comprehensive than the old website information. I'll try and get that pushed up somewhere so other people can dig into it too.

**Comment by Jonty** [comment]
FWIW the website is still showing #90, so it must have been the other merge that did it. I'd revert it and I'll take a deep look at this over the weekend if you like?

**Comment by danstowell** [comment]
This revert hasn't been merged, so no guarantee. Do what you like @Jonty, I'm stumped!

**Comment by yaxu** [comment]
I had the exact same problem with eulerroom.com - it must be a breaking
change in jekyll itself. I'll send a pull request now that should fix it.

On 3 February 2016 at 12:11, danstowell notifications@github.com wrote:

> This revert hasn't been merged, so no guarantee. Do what you like @Jonty
> https://github.com/Jonty, I'm stumped!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dorkbotlondon/dorkbotlondon.github.io/pull/4#issuecomment-179190844
> .

## 

http://yaxu.org/

**Comment by yaxu** [comment]
Yes that's fixed it, sorry it seems I'm a member of this project and made the change directly without realising it wasn't a PR

**Comment by yaxu** [comment]
Would love to see that mbox archive btw @jonty!

**Comment by danstowell** [comment]
@yaxu ex machina!

(PS yeah looking forward to the .mbox)

**Comment by Jonty** [comment]
Oh excellent work @yaxu! Saved me a horrid hour or so.

Will shove the mbox up later today.

**Pull request closed without merging**
